on: 
  workflow_dispatch:


jobs:

  FingerPrint:
    name: Fingerprint
    runs-on: ubuntu-latest
    steps:

    
    - name: Checkout Repo
      uses: actions/checkout@v5.0.0

  
    - name: Fingerprint
      run: |
        rm -f wappalyzer.txt 
        sudo apt update
        sudo apt install pipx 
        sudo rm /usr/bin/geckodriver
        wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.36.0-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/bin/
        geckodriver --version
        pipx install wappalyzer
        echo "-------------------------------"
        echo "Check Disk Space"
        df -h
        echo "-------------------------------"
        echo "Starting wappalyzer"
        echo "-------------------------------"
        hosts=$(cat live_hosts.txt)
        for host in $hosts; do
          echo "Scanning $host"
          wappalyzer -i "$host" >> wappalyzer.txt
          tail wappalyzer.txt -n 1 
        done
        
         
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: wappalyzer-scan
        path: |
          wappalyzer.txt
          
     







