on: 
  workflow_dispatch:


jobs:

  FingerPrint:
    name: Fingerprint
    runs-on: ubuntu-latest
    steps:

    
    - name: Checkout Repo
      uses: actions/checkout@v5.0.0

  
    - name: Fingerprint
      run: |
        rm -f wappalyzer.txt *.csv tomnom.txt
        sudo apt update
        sudo apt install pipx whatweb git nodejs npm 
        pipx ensurepath
        sudo rm /usr/bin/geckodriver
        wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.36.0-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/bin/
        geckodriver --version
        pipx install wappalyzer
        echo "-------------------------------"
        echo "Starting wappalyzer"
        echo "-------------------------------"
        hosts=$(cat live_hosts.txt)
        for host in $hosts; do
          echo "Scanning $host"
          wappalyzer -i "$host" >> wappalyzer.txt
        done
        sudo npm install -g yarn 
        echo "Yarn version is:"
        yarn --version
        git clone https://github.com/wappalyzer/wappalyzer.git
        cd wappalyzer
        yarn install
        yarn run link
        echo "Starting tomnom wappalyzer"
        for host in $hosts; do
          echo "Scanning $host using tomnom wappalyzer"
          node src/drivers/npm/cli.js "$host" >> tomnom.txt
        done

        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: wappalyzer-scan
        path: |
          wappalyzer.txt
          tomnom.txt
     







